// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package models

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestSystemCollectionFilter(t *testing.T) {
	t.Run("Should return System that fulfills given condition", func(t *testing.T) {
		testedCollection := SystemCollection{
			new(System),
			new(System),
		}

		t.Run("When given condition match everything", func(t *testing.T) {
			fileredCollection := testedCollection.Filter(func(user *System) bool { return true })
			assert.EqualValues(t, testedCollection, fileredCollection)
		})

		t.Run("When given condition match nothing", func(t *testing.T) {
			fileredCollection := testedCollection.Filter(func(user *System) bool { return false })
			emptyCollection := SystemCollection{}
			assert.EqualValues(t, emptyCollection, fileredCollection)
		})
	})
}

func TestUserCollectionFilter(t *testing.T) {
	t.Run("Should return User that fulfills given condition", func(t *testing.T) {
		testedCollection := UserCollection{
			new(User),
			new(User),
		}

		t.Run("When given condition match everything", func(t *testing.T) {
			fileredCollection := testedCollection.Filter(func(user *User) bool { return true })
			assert.EqualValues(t, testedCollection, fileredCollection)
		})

		t.Run("When given condition match nothing", func(t *testing.T) {
			fileredCollection := testedCollection.Filter(func(user *User) bool { return false })
			emptyCollection := UserCollection{}
			assert.EqualValues(t, emptyCollection, fileredCollection)
		})
	})
}

func TestReservationCollectionFilter(t *testing.T) {
	t.Run("Should return Reservation that fulfills given condition", func(t *testing.T) {
		testedCollection := ReservationCollection{
			new(Reservation),
			new(Reservation),
		}

		t.Run("When given condition match everything", func(t *testing.T) {
			fileredCollection := testedCollection.Filter(func(user *Reservation) bool { return true })
			assert.EqualValues(t, testedCollection, fileredCollection)
		})

		t.Run("When given condition match nothing", func(t *testing.T) {
			fileredCollection := testedCollection.Filter(func(user *Reservation) bool { return false })
			emptyCollection := ReservationCollection{}
			assert.EqualValues(t, emptyCollection, fileredCollection)
		})
	})
}
